smallrye/smallrye-common

constraint/src/main/java/io/smallrye/common/constraint/Assert.java
=> Print correct boolean expression in assert fail

annotation/src/main/java/io/smallrye/common/annotation/Experimental.java
Per https://github.com/smallrye/smallrye-common/pull/26#discussion_r416338911
=> Add FIELD and PACKAGE targets to Experimental annotation

os/pom.xml, os/src/main/java/io/smallrye/common/os/GetProcessInfoAction.java, os/src/main/java/io/smallrye/common/os/OS.java, os/src/main/java/io/smallrye/common/os/Process.java, os/src/main/java/io/smallrye/common/os/ProcessRedirect.java, os/src/main/java/io/smallrye/common/os/package-info.java, os/src/main/java9/io/smallrye/common/os/GetProcessInfoAction.java, os/src/main/java9/io/smallrye/common/os/ProcessRedirect.java, os/src/test/java/io/smallrye/common/os/OSTest.java, os/src/test/java/io/smallrye/common/os/ProcessTest.java, pom.xml
This contains OS related utilities (like detecting the Operating System it runs on and Process-related operations)
=> Introduce OS module

.github/workflows/build.yml
This will speed up the PR builds significantly
=> Cache maven local repository between builds

classloader/src/main/java/io/smallrye/common/classloader/ClassPathUtils.java
This avoids opening a filesystem just to read one specific file.
Same idea as done in quarkus: https://github.com/quarkusio/quarkus/pull/22262
Saves about 10ms of quarkus startup time in fast-jar mode (on windows).
=> Use URLConnection to read jar content

pom.xml, vertx-context/pom.xml, vertx-context/src/main/java/io/smallrye/common/vertx/ContextLocals.java, vertx-context/src/main/java/io/smallrye/common/vertx/VertxContext.java, vertx-context/src/test/java/io/smallrye/common/vertx/ContextLocalsTest.java, vertx-context/src/test/java/io/smallrye/common/vertx/VertxContextTest.java
=> Provide utilities to properly use Vert.x duplicated context and Context locals

pom.xml, version/src/main/java/io/smallrye/common/version/MavenVersionIterator.java, version/src/test/java/io/smallrye/common/version/MavenVersionTest.java
See [MNG-7700](https://issues.apache.org/jira/browse/MNG-7700) and [MNG-7701](https://issues.apache.org/jira/browse/MNG-7701).
=> Improve canonicalization of Maven version strings; skip known bugs

net/src/main/java/io/smallrye/common/net/Substitutions.java
=> Fix substitutions for Windows OS

function/pom.xml, function/src/main/java/io/smallrye/common/function/Functions.java, function/src/main/java/io/smallrye/common/function/FunctionsLogging.java, message-ranges.txt
This avoids additional CL in Quarkus
=> Use @MessageLogger to log messages in function module

pom.xml, version/pom.xml, version/src/main/java/io/smallrye/common/version/AbstractVersionScheme.java, version/src/main/java/io/smallrye/common/version/MavenVersionIterator.java, version/src/main/java/io/smallrye/common/version/MavenVersionScheme.java, version/src/test/java/io/smallrye/common/version/MavenVersionTest.java
=> Switch from `maven-artifact` to `maven-resolver` version scheme

.github/workflows/build.yml, cpu/src/test/java/io/smallrye/common/cpu/CPUTests.java
Also fix CI so that if the macos tests run on aarch64, it still works.
=> Fix CPU test to allow multiple valid CPU types

constraint/src/main/java/io/smallrye/common/constraint/Messages.java, expression/src/main/java/io/smallrye/common/expression/Messages.java, net/src/main/java/io/smallrye/common/net/Messages.java, pom.xml, version/src/main/java/io/smallrye/common/version/Messages.java
Also make necessary changes for JPMS support.
=> Bump `org.jboss.logging:jboss-logging` to 3.6.0.Final

.github/workflows/release-perform.yml, .github/workflows/release-prepare.yml
=> Split Release Workflow

.github/workflows/release-perform.yml
=> Remove dryRun flag in release-perform.yml

resource/src/main/java/io/smallrye/common/resource/JarFileResourceLoader.java, resource/src/main/java/io/smallrye/common/resource/PathResourceLoader.java, resource/src/main/java/io/smallrye/common/resource/ResourceLoader.java, resource/src/main/java/io/smallrye/common/resource/URLResourceLoader.java
This will allow for easier construction of protection domains for class loading, and may be useful in other contexts.
=> Add resource loader method to get base URL

.github/workflows/build.yml
=> Fix javadoc issue by swapping task order

resource/src/main/java/io/smallrye/common/resource/JarFileResourceLoader.java
=> Use `JarFile.OPEN_READ` instead of `ZipFile`

cpu/src/main/java/module-info.java
This time I got it right. Probably.
=> Fix (again) invalid module name

.github/workflows/pre-release.yml, .github/workflows/release-perform.yml, .github/workflows/release-prepare.yml, .github/workflows/release.yml, version/src/main/java/io/smallrye/common/version/AbstractVersionIterator.java, version/src/main/java/io/smallrye/common/version/MavenVersionIterator.java, version/src/main/java/io/smallrye/common/version/MavenVersionScheme.java, version/src/test/java/io/smallrye/common/version/MavenVersionTest.java
=> Backports to 2.16.x

process/src/main/java/io/smallrye/common/process/ArgumentRule.java, process/src/main/java/io/smallrye/common/process/PipelineRunner.java, process/src/main/java/io/smallrye/common/process/ProcessBuilderImpl.java, process/src/test/java/io/smallrye/common/process/WindowsSpecificTests.java, process/src/test/resources/batch/echo_2_args.cmd, process/src/test/resources/batch/hello_world.cmd, process/src/test/resources/powershell/echo_args.ps1, process/src/test/resources/powershell/hello_world.ps1
This is only the minimum level of basic support. There are more things that can be done to enhance this, so it does not fully address #428 but it does partially resolve it.
=> Support execution of batch and powershell scripts
