.github/workflows/build.yml
.github/workflows/release.yml
pom.xml

Require Java 11 to build

---

.github/workflows/build.yml

Due to the `smallrye-common-io` proposed changes (#36 / #37)

Update build.yml to support JDK 9/10 testing

---

.github/workflows/build.yml

This allows us to have a consistent & functional env var for the JDK installation.

Use AdoptOpenJDK's Java setup

---

classloader/pom.xml
classloader/src/main/java/io/smallrye/common/classloader/ClassDefiner.java
classloader/src/main/java/io/smallrye/common/classloader/DefineClassPermission.java
classloader/src/main/java9/io/smallrye/common/classloader/ClassDefiner.java
classloader/src/test/java/io/smallrye/common/classloader/ClassDefinerTest.java
pom.xml

This is just a proposal to start the discussion on how we want to support this. The main motivator is the mapping feature in SmallRye Config:
https://github.com/radcortez/smallrye-config/commit/b5dea58d990ab71691f955f4b5fa20810fd6f037#r40821102

Support defining classes in multiple JDK versions.

---

annotation/src/main/java/io/smallrye/common/annotation/Blocking.java
annotation/src/main/java/io/smallrye/common/annotation/NonBlocking.java

Follow-up on the discussion from https://github.com/quarkusio/quarkus/pull/12418.
Add the `@Blocking` and `@NonBlocking` annotation.
@Ladicek Can you check and comment? 
@mkouba I dropped the Qualifier part for now (hopefully for good). I will see how I can work around this in Quarkus-gRPC (@michalszynkiewicz  FYI).

Add the @Blocking and @NonBlocking annotations

---

os/src/main/java/io/smallrye/common/os/GetAllProcessesInfoAction.java
os/src/main/java/io/smallrye/common/os/GetProcessInfoAction.java
os/src/main/java/io/smallrye/common/os/Process.java
os/src/main/java/io/smallrye/common/os/ProcessInfo.java
os/src/main/java9/io/smallrye/common/os/GetAllProcessesInfoAction.java
os/src/main/java9/io/smallrye/common/os/GetProcessInfoAction.java
os/src/test/java/io/smallrye/common/os/ProcessTest.java

Introduce Process.getAllProcess

---

annotation/pom.xml
annotation/src/main/java/io/smallrye/common/annotation/Identifier.java

This is an alternative to `@Named`. Unlike `@Named`, it is a proper
qualifier in CDI environment.

Add @Identifier

---

pom.xml
ref/pom.xml
ref/src/main/java/io/smallrye/common/ref/CleanerReference.java
ref/src/main/java/io/smallrye/common/ref/PhantomReference.java
ref/src/main/java/io/smallrye/common/ref/Reapable.java
ref/src/main/java/io/smallrye/common/ref/Reaper.java
ref/src/main/java/io/smallrye/common/ref/Reference.java
ref/src/main/java/io/smallrye/common/ref/References.java
ref/src/main/java/io/smallrye/common/ref/SoftReference.java
ref/src/main/java/io/smallrye/common/ref/StrongReference.java
ref/src/main/java/io/smallrye/common/ref/WeakReference.java
ref/src/main/java/io/smallrye/common/ref/package-info.java

This would replace usages of `wildfly-common`'s `ref` subpackage.

Introduce reference support submodule

---

annotation/src/main/java/io/smallrye/common/annotation/CheckReturnValue.java

IntelliJ at least cannnot "see" the docs on this element because they appear after annotations.

Fix JavaDoc formatting issue

---

expression/pom.xml
expression/src/main/java/module-info.yml
net/pom.xml
net/src/main/java/module-info.yml
pom.xml
version/pom.xml
version/src/main/java/module-info.yml
vertx-context/pom.xml
vertx-context/src/main/java/module-info.yml

Fixes #158.
~~This is a draft until the JBoss Logging release trickles out to Maven Central.~~
JBoss Logging requires Java 11 as of version 3.5.0.Final; thus this PR now depends on #153.

Finish remaining `module-info` descriptors

---

ref/src/main/java/io/smallrye/common/ref/References.java

- This creates a single Reference Reaper thread instead of 3 (as discussed in
https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Reference.20Reaper.201-3)

Create one Reference Reaper thread

---

.github/workflows/build.yml

With this change, we build the project using Java 17 and test it on both Java 17 and Java 11 on all three supported OSes.

Use multi-JDK support for testing, configurable Maven version

---

net/src/main/java/io/smallrye/common/net/Inet.java

Twin of https://github.com/quarkusio/quarkus/pull/38191

Remove indify string concatenation on Inet::getInet4Address

---

.github/workflows/build.yml
cpu/pom.xml
cpu/src/main/java/io/smallrye/common/cpu/CPU.java
cpu/src/test/java/io/smallrye/common/cpu/CPUTests.java

As we start to use FFM, it may be useful to have a centralized and reliable means of detecting information about the current CPU architecture.

Add CPU detection

---

constraint/pom.xml
constraint/src/main/java/io/smallrye/common/constraint/Assert.java
pom.xml

This is a backwards-compatible change using the `bridger` tool. See https://www.morling.dev/blog/refining-return-type-java-methods-without-breaking-backwards-compatibility/ for more information about retaining binary compatibility using bridge methods.

Change the return type of certain `Assert` methods.

---

net/src/main/java/io/smallrye/common/net/Inet.java

Also, use the new API to construct the global IP address constants, to avoid unnecessary `String` construction.
Supercedes #276.

Provide API to construct IP addresses from host name and segments

---

classloader/src/main/java/io/smallrye/common/classloader/ClassPathUtils.java

Avoid NPE if the class loader is `null`

---

.github/dependabot.yml

It makes it harder to exclude certain versions and consider changes independently. This was an experiment; the experiment failed.

Discontinue dependabot grouping

---

classloader/src/main/java/io/smallrye/common/classloader/ClassPathUtils.java

* Make sure that `jar:file:///...` are properly formed (the sub-URL must have a scheme of `file`)
* When there is no `!` in the JAR URL, treat the file as a JAR and process its root path
* Otherwise recursively resolve each segment which is `!`-terminated
Fixes #289

Support multiple nesting of JAR files

---

os/src/main/java/io/smallrye/common/os/Linux.java

Add detection for WSL

---

pom.xml
resource/pom.xml
resource/src/main/java/io/smallrye/common/resource/EmptyDirectoryStream.java
resource/src/main/java/io/smallrye/common/resource/JarFileResource.java
resource/src/main/java/io/smallrye/common/resource/JarFileResourceLoader.java
resource/src/main/java/io/smallrye/common/resource/MappedDirectoryStream.java
resource/src/main/java/io/smallrye/common/resource/MemoryInputStream.java
resource/src/main/java/io/smallrye/common/resource/MemoryResource.java
resource/src/main/java/io/smallrye/common/resource/PathResource.java
resource/src/main/java/io/smallrye/common/resource/PathResourceLoader.java
resource/src/main/java/io/smallrye/common/resource/Resource.java
resource/src/main/java/io/smallrye/common/resource/ResourceLoader.java
resource/src/main/java/io/smallrye/common/resource/ResourceURLConnection.java
resource/src/main/java/io/smallrye/common/resource/ResourceURLStreamHandler.java
resource/src/main/java/io/smallrye/common/resource/ResourceUtils.java
resource/src/main/java/io/smallrye/common/resource/URLResource.java
resource/src/main/java/io/smallrye/common/resource/URLResourceLoader.java
resource/src/main/java/module-info.yml
resource/src/test/java/io/smallrye/common/resource/JarFileResourceLoaderTests.java
resource/src/test/java/io/smallrye/common/resource/ResourceUtilsTests.java

Proposed resource API. Provides a uniform API for reading resources from the class path or filesystem.
Non-goals are presently including:
- Support for writing

Resource API

---

.github/workflows/build.yml

Otherwise JavaDoc checks fail after release.

Fix "quality" build job to use correct JDK

---

README.adoc

Add BOM to README.adoc

---

net/pom.xml
pom.xml
ref/pom.xml

The dependency has the needed annotations/classes

Use `org.graalvm.sdk:nativeimage` instead of `org.graalvm.sdk:graal-sdk`

---

version/src/main/java/io/smallrye/common/version/AbstractVersionIterator.java
version/src/main/java/io/smallrye/common/version/VersionScheme.java

- Resolves the build errors and warnings reported in https://github.com/smallrye/smallrye-common/actions/runs/10063852406/job/27819648461

Resolve Javadoc quality issues

---

os/src/main/java/io/smallrye/common/os/Process.java

Fixes performance problem when creating log records or other things which frequently request the PID or process name.
See quarkusio/quarkus#42858 for more info.

Cache current process handle

---

classloader/src/main/java/io/smallrye/common/classloader/ClassPathUtils.java

See https://github.com/quarkusio/quarkus/issues/42248#issuecomment-2315352414 for details.
/cc @rsvoboda

Only process a path as a JAR if it exists and is a regular file

---

net/src/main/java/io/smallrye/common/net/CidrAddress.java

This will give the same result, however there are certain cases where using `signum` for comparisons fails, so it is best to stick with `Integer.compare` even if it is not a specific problem in this case.
While we're in here, we can also use `Byte.toUnsignedInt` for further code clarity in these cases.

Use `compare` instead of `signum`

---

expression/src/main/java/io/smallrye/common/expression/Expression.java
expression/src/test/java/io/smallrye/common/expression/ExpressionTestCase.java

Proposal of a new escape expressions mode (`NO_$$`) to help with:
- https://github.com/smallrye/smallrye-config/issues/1219
- https://github.com/smallrye/smallrye-config/issues/746
- https://github.com/smallrye/smallrye-config/issues/1056
- https://github.com/quarkusio/quarkus/issues/41883
Activating `NO_$$` will effectively disable the `$$` escape used for expressions.
This also allows the removal of the workaround for MP Config:
https://github.com/smallrye/smallrye-config/blob/d447b0c346e39a09c6d07c7d5ce8186bd4154037/implementation/src/main/java/io/smallrye/config/ExpressionConfigSourceInterceptor.java#L102-L123

Expression NO_$$ mode

---

annotation/src/main/java/io/smallrye/common/annotation/Experimental.java
annotation/src/main/java/io/smallrye/common/annotation/TechPreview.java

Annotated elements are feature-complete, but have known limitations, need bake-time or have rough angles. The API is more stable than with @Experimental. Tech preview API can still be changed, but changes will be communicated.

Introduce an annotation to mark a feature as tech preview

---

.github/project.yml

This is expected to be the final release before moving to Java 17. See #349.

Release 2.8.0

---

resource/src/main/java/io/smallrye/common/resource/JarFileResource.java
resource/src/main/java/io/smallrye/common/resource/Resource.java

This allows for secure (spec-compliant) class loader implementation by allowing correct protection domains to be defined.

Add resource method to list code signers

---

.github/workflows/build.yml
annotation/pom.xml
annotation/src/main/java/module-info.java
constraint/pom.xml
constraint/src/main/java/module-info.java
constraint/src/main/java/module-info.yml
cpu/pom.xml
cpu/src/main/java/module-info.java
expression/pom.xml
expression/src/main/java/module-info.java
expression/src/main/java/module-info.yml
function/pom.xml
function/src/main/java/module-info.java
function/src/main/java/module-info.yml
net/pom.xml
net/src/main/java/module-info.java
net/src/main/java/module-info.yml
ref/pom.xml
ref/src/main/java/module-info.java
ref/src/main/java/module-info.yml
resource/src/main/java/module-info.java
resource/src/main/java/module-info.yml
version/pom.xml
version/src/main/java/module-info.java
version/src/main/java/module-info.yml
vertx-context/pom.xml
vertx-context/src/main/java/module-info.java
vertx-context/src/main/java/module-info.yml

Fixes #348, and some other minor issues as well

Move baseline to Java 17

---

resource/src/main/java/io/smallrye/common/resource/PathResource.java
resource/src/test/java/io/smallrye/common/resource/PathResourceLoaderTests.java

This avoids a potential problem where e.g. filesystem locks are taken by the JDK's caching implementation.
See quarkusio/quarkus#43940 for an example.

Always use a URL stream handler for path-based resources

---

resource/src/main/java/io/smallrye/common/resource/PathResourceLoader.java

Do not return a resource for non-existent filesystem files

---

resource/src/main/java/io/smallrye/common/resource/ResourceUtils.java

We sometimes need to canonicalize a path before handing it off to the resource loader. So, make the method public to avoid duplication.

Make `ResourceUtils` public

---

classloader/pom.xml
classloader/src/main/java/module-info.java
io/pom.xml
io/src/main/java/module-info.java
os/pom.xml
os/src/main/java/module-info.java
pom.xml

* Fully modularize modules which did not previously have `module-info.yml`
* Disable JavaDoc legacy mode

Fix release build

---

resource/src/main/java/io/smallrye/common/resource/JarFileResourceLoader.java

Currently it is only opened as an MR JAR when loaded from the filesystem due to an oversight.

Open JAR in MR mode in all situations

---

.github/workflows/build.yml
cpu/pom.xml
cpu/src/main/java/io/smallrye/common/cpu/CPU.java
cpu/src/main/java/io/smallrye/common/cpu/JDK22Specific.java
cpu/src/main/java/module-info.java
cpu/src/main/java22/io/smallrye/common/cpu/JDK22Specific.java
cpu/src/main/java22/module-info.java
pom.xml

Stop using `Unsafe` starting with Java 22. Update CI to run with Java 23 (latest), 21 (LTS), and 17 (LTS) to verify that `Unsafe` is not being used and no warning is printed.

Do not use Unsafe on Java 22+

---

classloader/src/main/java/io/smallrye/common/classloader/ClassPathUtils.java

This shouldn't make a difference in the real world, but those method handles sure don't look nice in
flamegraphs

Avoid using lambdas and streams in <clinit>

---

ref/src/main/java/io/smallrye/common/ref/References.java

The flamegraph of the existing situation:
becomes:

Slightly reduce the startup cost of the modules used in Quarkus

---

cpu/src/main/java/io/smallrye/common/cpu/CacheInfo.java

This feature has a measurable startup performance
and for most modern CPUs, the cache line size is
64 anyway, so it doesn't make sense burning cycles to figure it out just for the odd case were the value is different

Make CPU cache interrogation an opt-in feature

---

function/src/main/java/io/smallrye/common/function/ExceptionObjIntFunction.java
function/src/main/java/io/smallrye/common/function/ExceptionObjIntPredicate.java
function/src/main/java/io/smallrye/common/function/ExceptionObjLongFunction.java
function/src/main/java/io/smallrye/common/function/ExceptionObjLongPredicate.java
function/src/main/java/io/smallrye/common/function/ObjIntFunction.java
function/src/main/java/io/smallrye/common/function/ObjIntPredicate.java
function/src/main/java/io/smallrye/common/function/ObjLongFunction.java
function/src/main/java/io/smallrye/common/function/ObjLongPredicate.java
pom.xml
search/pom.xml
search/src/main/java/io/smallrye/common/search/BinarySearch.java
search/src/main/java/module-info.java
search/src/test/java/io/smallrye/common/search/TestIntRange.java
search/src/test/java/io/smallrye/common/search/TestLongRange.java
search/src/test/java/io/smallrye/common/search/TestObjRange.java

Will update the summary/description once things are more finalized.
Design (short version):
* `BinarySearch.intRange().find(0, 100, n -> n >= 35)` - find the first integer in range `[0, 100)` which satisfies the predicate `n >= 35` (in this case, yields 35 after about 7 steps)
* `BinarySearch.longRange().find(1000L, 1000000L, n -> n >= 2048L)` - find the first long integer in range `[1000L, 1000000L)` which satisfies the predicate `n >= 2048L`
We also have `BinarySearch.intRange().unsigned()` which treats the range as unsigned integers (`0..0xFFFF_FFFF`), and `BinarySearch.longRange().unsigned()` which is equivalent for `long`.
There are also variations which allow you to provide your own midpoint function.
There are helpers to search ranges of things, for example, given:
```java
public …
```

Binary search API

---

vertx-context/src/main/java/io/smallrye/common/vertx/ContextLocals.java
vertx-context/src/main/java/io/smallrye/common/vertx/VertxContext.java
vertx-context/src/test/java/io/smallrye/common/vertx/ContextLocalsNestedContextTest.java

Initial implementation of #402.

Provide the nested context API

---

annotation/pom.xml
pom.xml
vertx-context/pom.xml

I specifically chose Jandex 3.1 because Quarkus 3.8 is still on that version. Quarkus 3.15 is on Jandex 3.2, so that would also be an option, but the classes in this project are not very complex and no new features added in later Jandex versions would be useful.

update Jandex to 3.1.8

---

process/src/main/java/io/smallrye/common/process/ArgumentRule.java
process/src/main/java/io/smallrye/common/process/PipelineBuilder.java
process/src/main/java/io/smallrye/common/process/PipelineRunner.java
process/src/main/java/io/smallrye/common/process/ProcessBuilder.java
process/src/main/java/io/smallrye/common/process/ProcessBuilderImpl.java
process/src/test/java/io/smallrye/common/process/WindowsSpecificTests.java

There are two wrong ways to do it; this way the user can pick their poison.

Hide Windows batch argument escaping behind an option
